name: build-and-deploy
run-name: ${{ github.actor }} is building and deploying ${{ github.event.repository.name }}

env:
  DOCKER_IMAGE: simhub-client
  DOCKER_CONTAINER: simhub-client

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker buildx build --platform linux/amd64,linux/arm64 --push --tag ${{ env.DOCKER_IMAGE }}:latest .
