name: build-and-deploy
run-name: ${{ github.actor }} is building and deploying ${{ github.event.repository.name }}

env:
  DOCKER_IMAGE: simhub-client
  DOCKER_CONTAINER: simhub-client

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: self-hosted

    name: build
    steps:
      -  uses: actions/checkout@v3
      - run: >
          docker build -t ${{ env.DOCKER_IMAGE }}:development .